//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public short Transactionid { get; set; }
        public Nullable<short> Book { get; set; }
        public string Transtype { get; set; }
        public Nullable<System.DateTime> Transdate { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Book Book1 { get; set; }
    }
}
